environment:
  matrix:
    - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --frozen-lockfile

test_script:
  - node --version
  - yarn --version

build: off

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
